CREATE TABLE IF NOT EXISTS `player_history_skill` (
	  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	  `player_id` int(11) NOT NULL,
	  `lastlogin` bigint(20) unsigned NOT NULL,
	  `lastlogout` bigint(20) unsigned NOT NULL,
	  `town_id` int(11) NOT NULL,
	  `lastip` int(10) unsigned NOT NULL,
	  `skull` tinyint(1) NOT NULL,
	  `blessings` tinyint(2) NOT NULL,
	  `onlinetime` int(11) NOT NULL,
	  `balance` bigint(20) unsigned NOT NULL,
	  `level` int(11) NOT NULL,
	  `experience` bigint(20) NOT NULL,
	  `maglevel` int(11) NOT NULL,
	  `skill_fist` int(10) unsigned NOT NULL,
	  `skill_club` int(10) unsigned NOT NULL,
	  `skill_sword` int(10) unsigned NOT NULL,
	  `skill_axe` int(10) unsigned NOT NULL,
	  `skill_dist` int(10) unsigned NOT NULL,
	  `skill_shielding` int(10) unsigned NOT NULL,
	  `skill_fishing` int(10) unsigned NOT NULL,
	  PRIMARY KEY (`id`),
	  FOREIGN KEY (`player_id`) REFERENCES `players` (`id`) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8;